services:
  db:
    image: postgres:16-alpine
    container_name: meeting_system_db
    restart: always
    environment:
      POSTGRES_USER: yebsoft_user
      POSTGRES_PASSWORD: YebsoftSecretPassword2026!
      POSTGRES_DB: meeting_system_prod
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U yebsoft_user -d meeting_system_prod" ]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    image: meeting_system_api:latest
    container_name: meeting_system_api
    restart: always
    environment:
      - DATABASE_URL=postgresql://yebsoft_user:YebsoftSecretPassword2026!@db:5432/meeting_system_prod
      - SECRET_KEY=yebsoft_super_secure_crypto_secret_key_2026_jwt
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - AVATAR_UPLOAD_DIR=app/static/avatars
      - DB_MAX_OVERFLOW=10
      - DB_POOL_RECYCLE=3600
      - DB_POOL_SIZE=20
      - DB_POOL_TIMEOUT=30
    volumes:
      - ./avatars_data:/workspace/app/static/avatars
      - ./uploads_data:/workspace/uploads
    depends_on:
      db:
        condition: service_healthy

  coturn:
    image: coturn/coturn:latest
    container_name: meeting_system_coturn
    restart: always
    ports:
      - "3478:3478/tcp"
      - "3478:3478/udp"
      - "5349:5349/tcp"
      - "5349:5349/udp"
      - "49152-49200:49152-49200/udp"
    command:
      - -n
      - --log-file=stdout
      - --lt-cred-mech
      - --fingerprint
      - --realm=turn.yebsoft.com
      - --user=yebsoft_turn_user:yebsoft_turn_password_2026

  nginx:
    image: nginx:alpine
    container_name: meeting_system_nginx
    restart: always
    ports:
      - "8090:80"
      - "443:443"
    entrypoint: [ "/bin/sh", "/etc/nginx/nginx-entrypoint.sh" ]
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx-entrypoint.sh:/etc/nginx/nginx-entrypoint.sh:ro
      - ./certbot_certs:/etc/letsencrypt
      - ./certbot_www:/var/www/certbot
    depends_on:
      - web
