"""fix_meeting_actions_columns

Revision ID: 3e0662bd2725
Revises: 8e4ba53890f5
Create Date: 2026-07-17 09:36:40.207685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e0662bd2725'
down_revision: Union[str, Sequence[str], None] = '8e4ba53890f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting_actions', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('meeting_actions', sa.Column('title', sa.String(), nullable=False))
    op.add_column('meeting_actions', sa.Column('description', sa.Text(), nullable=True))
    op.create_index(op.f('ix_meeting_actions_title'), 'meeting_actions', ['title'], unique=False)
    op.create_foreign_key(None, 'meeting_actions', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.drop_column('meeting_actions', 'action_item')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('meeting_actions', sa.Column('action_item', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'meeting_actions', type_='foreignkey')
    op.drop_index(op.f('ix_meeting_actions_title'), table_name='meeting_actions')
    op.drop_column('meeting_actions', 'description')
    op.drop_column('meeting_actions', 'title')
    op.drop_column('meeting_actions', 'created_by')
    # ### end Alembic commands ###
